//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace huy.CodeGen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test")]
        public string GA_DbName {
            get {
                return ((string)(this["GA_DbName"]));
            }
            set {
                this["GA_DbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client")]
        public string GA_ClientNamespace {
            get {
                return ((string)(this["GA_ClientNamespace"]));
            }
            set {
                this["GA_ClientNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server")]
        public string GA_ServerNamespace {
            get {
                return ((string)(this["GA_ServerNamespace"]));
            }
            set {
                this["GA_ServerNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DTO")]
        public string GA_DtoNamespace {
            get {
                return ((string)(this["GA_DtoNamespace"]));
            }
            set {
                this["GA_DtoNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vi-VN")]
        public string GA_DefaultLanguage {
            get {
                return ((string)(this["GA_DefaultLanguage"]));
            }
            set {
                this["GA_DefaultLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestContext")]
        public string GA_DbContextName {
            get {
                return ((string)(this["GA_DbContextName"]));
            }
            set {
                this["GA_DbContextName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\PhuDinhClientServer\\Client\\Client\\View\\Gen")]
        public string GA_ViewPath {
            get {
                return ((string)(this["GA_ViewPath"]));
            }
            set {
                this["GA_ViewPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\PhuDinhClientServer\\Client\\Client\\ViewModel\\Gen")]
        public string GA_ViewModelPath {
            get {
                return ((string)(this["GA_ViewModelPath"]));
            }
            set {
                this["GA_ViewModelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\PhuDinhClientServer\\Client\\Client\\Text")]
        public string GA_TextPath {
            get {
                return ((string)(this["GA_TextPath"]));
            }
            set {
                this["GA_TextPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\PhuDinhClientServer\\Server\\src\\Server\\Controllers\\Gen")]
        public string GA_ControllerPath {
            get {
                return ((string)(this["GA_ControllerPath"]));
            }
            set {
                this["GA_ControllerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\PhuDinhClientServer\\Shared\\DTO\\Gen")]
        public string GA_DtoPath {
            get {
                return ((string)(this["GA_DtoPath"]));
            }
            set {
                this["GA_DtoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\PhuDinhClientServer\\Server\\src\\Server\\Entities\\Gen")]
        public string GA_EntityPath {
            get {
                return ((string)(this["GA_EntityPath"]));
            }
            set {
                this["GA_EntityPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\github\\ClientServerTemplate")]
        public string GA_ProjectPath {
            get {
                return ((string)(this["GA_ProjectPath"]));
            }
            set {
                this["GA_ProjectPath"] = value;
            }
        }
    }
}
